### ISSUE TITLE
README example .gpkg layer names 

### ISSUE THREAD

**Issue by dmragar** [CIROH-UA/ngen-datastream#101]
From the example in the README, a hydrofabric generated with: 
```
hfsubset -w medium_range -s nextgen -v 2.1.1 -l divides,flowlines,network,nexus,forcing-weights,flowpath-attributes,model-attributes -o ./palisade.gpkg -t hl "Gages-09106150"
```

has names: 
`flowpath-attributes` and `flowlines`, while datastream expects `flowpath_attributes` and `flowpaths`

Not sure if this is related to the hf version (2.1.1) called by `hfsubset`. Or perhaps fixed by changing the params to `-l` (not tested)

(@JordanLaserGit)

**Comment by JordanLaserGit** [comment]
I believe this is a mismatch between t-route and the [layers provided by hfsubset](https://www.lynker-spatial.com/data?path=hydrofabric%2Fv2.1.1%2Fnextgen%2F). t-route is looking for `flowpaths` and `flowpath_attributes`, but hfsubset is providing `flowlines` and `flowpath-attributes`. I think I noticed this same thing a few weeks back and started an issue [here](https://github.com/lynker-spatial/hfsubsetCLI/issues/36). @mikejohnson51 @program--
