### ISSUE TITLE
A Broken Link in ARCHITECTURE.md

### ISSUE THREAD

**Issue by imanmaghami** [CIROH-UA/ngen-datastream#143]
In ARCHITECTURE.md, "here" link (an example of that [here](https://github.com/CIROH-UA/ngen-datastream/tree/main/terraform/AWS_BASICS.md#machine-images-amis)) is broken. It is under "Here's a rough idea of the workflow once a user submits an execution to the AWS statemachine" (towards the end of bullet point 2). Please update the link.

**Comment by JordanLaserGit** [comment]
Fixed. Thanks @imanmaghami
