### ISSUE TITLE
Broken Prerequisites Link in GETTING_STARTED.md

### ISSUE THREAD

**Issue by imanmaghami** [CIROH-UA/ngen-datastream#144]
The [link](https://github.com/CIROH-UA/ngen-datastream/tree/main/terraform#prerequisites) to the prerequisites section at the beginning of the [GETTING_STARTED.md](https://github.com/CIROH-UA/ngen-datastream/blob/main/research_datastream/terraform/GETTING_STARTED.md) file is broken and needs to be updated with the correct path.

**Comment by JordanLaserGit** [comment]
Fixed/removed
