### ISSUE TITLE
Suggestions for Improving Documentation Clarity and Cohesiveness

### ISSUE THREAD

**Issue by imanmaghami** [CIROH-UA/ngen-datastream#145]
## Description:
As discussed with the developers, there are opportunities to enhance the documentation to make it clearer and more user-friendly, especially for new users. Below are some initial suggestions based on my experience and discussions so far. Additional ideas may emerge as the process continues, but these serve as examples for improvement:

### 1. Addition of a `terraform_BASICS.md` for Beginners:
As also suggested by the developer, including a dedicated document that covers Terraform basics would be immensely helpful for new users without prior Terraform experience. This addition would ensure a smoother onboarding process by bridging the knowledge gap for beginners, making it easier for them to get started with Terraform workflows.

### 2. Clearly Indicate Where Specific Tools Are Used (AWS Console or Terminal):
While it might seem intuitive, explicitly stating when and where the AWS Console or Terminal is needed would improve clarity. For example, in the [GETTING_STARTED.md](https://github.com/CIROH-UA/ngen-datastream/blob/main/research_datastream/terraform/GETTING_STARTED.md) file:
- It could explicitly state that users need to **log in to the AWS Console** as a prerequisite step at the beginning.
- When transitioning from the AWS Console to a terminal for SSH access, the documentation could clearly state, for example: *"Switch to your terminal and SSH into the instance using the provided key pair."*

These small but important clarifications can significantly reduce confusion for new users. It’s worth reviewing the entire documentation for similar instances where such transitions could be explicitly clarified.

### 3. Improve Documentation with Tested System Information:
To improve clarity and reproducibility, adding a section that specifies the operating system and terminal environment used during the documentation creation and command testing would be highly beneficial. For example:
- **Operating System**: Ubuntu 20.04 LTS (Linux), macOS Monterey, or Windows 11.
- **Terminal**: Bash, PowerShell, or Command Prompt.

It is possible that this information has been mentioned or implicitly alluded to elsewhere in the documentation, but I might have missed it. Even if it is already mentioned, it could be helpful to reiterate this information wherever necessary to ensure clarity. Regardless, it would be valuable to highlight key differences in running commands across platforms. For example:
- On **Linux/macOS**, commands split across multiple lines can work if each line ends with a `\` (backslash).
- On **Windows Command Prompt**, commands often need to be entered on a single line unless using a continuation character like `^`.

Explain these differences or provide platform-specific examples (e.g., one for Linux/macOS and another for Windows) would make it easier for users working on different systems to follow the steps without confusion.

### 4. Numbered Sections for Easier Navigation:
Adding numbered sections in the documentation would improve readability and make it easier for users to follow the steps in a sequential manner. While this is a personal suggestion and may not align with everyone's preference, numbering can be particularly helpful in complex workflows, ensuring users can track their progress more effectively.  

## Additional Notes:
Improving the documentation may require input from various users and some additional effort. I’m happy to contribute further by providing feedback, assisting with testing, or even drafting new sections if needed.

Thank you for considering these suggestions to enhance the documentation!

**Comment by JordanLaserGit** [comment]
@imanmaghami thanks for your detailed feedback. The following changes have been made:
* Terraform basics file added -> https://github.com/CIROH-UA/ngen-datastream/blob/main/research_datastream/terraform/TERRAFORM_BASICS.md
* AWS Basics updated -> https://github.com/CIROH-UA/ngen-datastream/blob/main/research_datastream/terraform/AWS_BASICS.md
* Clarification on AWS Console vs local linux terminal
* Numbering sections in GETTING_STARTED.md
