### ISSUE TITLE
nwmurl compatibility tests

### ISSUE THREAD

**Issue by JordanLaserGit** [CIROH-UA/ngen-datastream#31]
Tests need to be written to ensure all file path options that can be produced by [nwmurl](https://github.com/CIROH-UA/nwmurl) can be processed without error.

**Comment by jameshalgren** [comment]
... or, at least, that those that are supposed to be there can be processed without error. There are some use cases where nwmurl should produce a file path that doesn't exist yet or that isn't accessible to the generating client.

**Comment by JordanLaserGit** [comment]
Okay, then perhaps a check first to make sure the web address exists. If so, test forcingprocessor. I know it will crash if using a google bucket, so this issue was mostly a reminder to make sure all accessible files won't break the processor.

**Comment by JordanLaserGit** [comment]
Addressed in e4d320a225665257b874ba04103c89a4f87396de
