### ISSUE TITLE
Add data_dir if missing with up to date NGIAB if missing

### ISSUE THREAD

**Issue by ZacharyWills** [CIROH-UA/ngen-datastream#32]
<img width="1008" alt="Screenshot 2023-12-31 at 14 40 33" src="https://github.com/CIROH-UA/ngen-datastream/assets/60660437/cd98abcb-3dfe-4d0a-ad14-e4b239426abe">

By default we can just shove in the NGIAB defaults, then if CONUS is specified we can interpret the default CFE global config and let the user deal with any more specific configs. 

Ideally we can build it so that the script will run a CONUS CFE with "DAILY" and CONUS specified.

It'll make it easier to spin up a stream and then customize, rather than have the user kind of walking blind until they get something functional.

**Comment by ZacharyWills** [comment]
<img width="982" alt="Screenshot 2023-12-31 at 16 39 58" src="https://github.com/CIROH-UA/ngen-datastream/assets/60660437/a6040b18-38bf-45bb-9fb0-87efe6e6c31e">

If I attempt to give it a basic new dir location with nothing there, it fails to populate.

**Comment by JordanLaserGit** [comment]
This has been addressed in several recent commits.
