### ISSUE TITLE
Add some warning/documentation/default settings to protect from accidental resource over scheduling

### ISSUE THREAD

**Issue by jameshalgren** [CIROH-UA/ngen-datastream#40]
Downloading this repository to a basic laptop or desktop and turning it on will, in the current configuration, either not work or will consume every resource available to the computer and make it unusable. 

Let's update the documentation on the front to make that a little more clear and then, as an additional update, make sure it gives the user a little warning in the initial startup: "Hey, you are about to do something a little painful. You need to sign here on your RAM with this magic marker before we put you under."

**Comment by JordanLaserGit** [comment]
@jameshalgren I was just saying to @ZacharyWills that I need to add a disclaimer that is repo is designed for HPC. It's possible to throttle things to work on something like a laptop, but that really isn't the intention. Will address this soon.

**Comment by JordanLaserGit** [comment]
https://github.com/CIROH-UA/ngen-datastream/tree/main?tab=readme-ov-file#disclaimer

**Comment by JordanLaserGit** [comment]
https://github.com/CIROH-UA/ngen-datastream/commit/dcb7eeb5782373e6d5acad288c1b1971b384c8bf

process limit is in place upstream of NGIAB container

**Comment by JordanLaserGit** [comment]
https://github.com/CIROH-UA/NGIAB-CloudInfra/pull/112

and process limit on NGIAB
