### ISSUE TITLE
arm64 support in install script

### ISSUE THREAD

**Issue by arpita0911patel** [CIROH-UA/ngen-datastream#64]
For Mac with:
⇒  uname -m
arm64

Getting "Unsupported architecture: arm64" while running install.sh. Please update the script to support this.

**Comment by JordanLaserGit** [comment]
This script is intended for Amazon 2023 Linux (from the INSTALL.md -> "Steps may vary depending on your specific linux distribution"). My suggestion would be to follow the step-by-step directions and modify them to work with MacOS. I imagine the changes are few (probably just the package installer). We can add another install script for MacOS, but I think it makes sense that this responsibility is left to the user.
